version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./php/src:/var/www/html

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
volumes:
  db_data: